name: lib_assist_app
description: "A premium mobile companion for the Library Assistant desktop and web app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
